### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by MosesGit** [anastasiia-zolochevska/react-appinsights#11]
I don't think it is possible, but I just wanted to check. Is it possible to use Application Insights with React Native? When I attempt to use this library, I get some undefined variables (which is similar to what I get when using a library not compatible with React Native) so I don't think it is. I know there is a React Native SDK for App Center, but I was hoping to find some pure javascript to use with Expo without detaching.

**Comment by somanysteves** [comment]
@mchen37 did you ever figure out a solution to this?

**Comment by pviotti** [comment]
Reopening this issue, as it is worth investigating.

**Comment by somanysteves** [comment]
I'm actively working on it at the moment, it's definitely possible with reduced functionality. I'm not home atm but I'll respond in a few hours with more details. Short version is with the aisku (web version) of application insights js, some weird construction logic and a few small pull reqs , things like .trackPageView and .trackEvent do in fact work.

**Comment by somanysteves** [comment]
Ok, so this is very rough, but to get it working...
This repo:
https://github.com/shortstevenn/applicationinsights-channel-js
has changes to the application insights channel with an open pull request:
https://github.com/Microsoft/applicationinsights-channel-js/pull/43

Build that and drop the output into the build for:
https://github.com/shortstevenn/ApplicationInsights-JS/tree/feature/supporting-react-native
Which has changes that aren't pull request ready. I think I've broken the interface and need to fix that.

Then I have this class that I haven't submitted yet... (called ReactNativeAppInsights.js)
```
import { AppInsightsCore, DiagnosticLogger } from '@microsoft/applicationinsights-core-js'
import { ApplicationInsights as ApplicationInsightsInternal } from '@microsoft/applicationinsights-web';
import { Sender }  from "@microsoft/applicationinsights-channel-js";

global.window.location = global.window.location || {
    host: ""
}

const ApplicationInsights = () => insights;

var insights;
var initialized = false;

const BuildReactNativeAppInsights = function build(config) {
    if(!initialized) {
        var aiCore = new AppInsightsCore();
        config.logger = config.logger || new DiagnosticLogger();
        config.enableSessionStorageBuffer = false;

        var sender = new Sender(config, aiCore);
        sender.initialize(config, aiCore);
        aiCore.initialize(config, [sender]);
        insights = new ApplicationInsightsInternal(config);
    }
    initialized = true;
}

export { 
    ApplicationInsights,
    BuildReactNativeAppInsights, 
};
```

which gets called like this:
```
import { BuildReactNativeAppInsights, ApplicationInsights } from './ReactNativeAppInsights';

let config = {
  instrumentationKey: "my-instrumentation-key",
  loglevelConsole:2,
  loggingLevelTelemetry:2
};

describe('ReactNativeAppInsightsBuilder', () => {
  it('Constructs without crashing', () => { 
    BuildReactNativeAppInsights(config);
  }),

  it('Tracks a page view', () => { 
    BuildReactNativeAppInsights(config);
    ApplicationInsights.trackPageView({name: "MyPage"});
  })
});
```

I wasn't doing the pull request yet because I'm still trying to make it work with [https://github.com/Azure/react-appinsights](url)

So yea, remember, _you_ asked...

edit, if you want it to work with jest, you need to do something like this in setupTests
```
const mockXHR = {
  open: jest.fn(),
  send: jest.fn(),
  readyState: 4,
  responseText: JSON.stringify(
      []
  ),
  withCredentials: false,
  setRequestHeader: jest.fn()
};
window.XMLHttpRequest = jest.fn(() => mockXHR);
```

**Comment by pviotti** [comment]
Haha ok. Sounds a bit complicated but kudos for the effort!  👍 
If it is of any help, we're working on a rewrite of react-appinsights in Typescript, with various fixes and support for AISKU Web in the `typescript-rewrite` branch. So I suggest using that branch as target if you raise any PR on react-appinsights.

**Comment by somanysteves** [comment]
Thanks, I'll sync that branch and try it out. Do you guys already plan to support react-native? I don't want to duplicate effort (poorly).

**Comment by pviotti** [comment]
It would be great to support it but for the moment it's not something we planned or put effort into.  
So... we welcome contributions :)

**Comment by pviotti** [comment]
Closing this since it looks like this has been implemented as an extension whose code is currently in the Application Insights JS SDK monorepo: https://github.com/Microsoft/ApplicationInsights-JS/tree/master/vNext/extensions/applicationinsights-react-native
