### ISSUE TITLE
How to use with router v4?

### ISSUE THREAD

**Issue by georgiosd** [anastasiia-zolochevska/react-appinsights#12]
Hi!

`react-router` v4 removes both `browserHistory` and `on*` events and instead recommends to use `componentWillMount` - any chance you will be updating the library to do this?

**Comment by pviotti** [comment]
I've tried to cope with this change by following the [migration guidelines](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md#on-properties) of react-router.  
Regarding the support for browserHistory, see the [readme](https://github.com/Azure/react-appinsights#track-router-changes).  
This changes are included in v2.0.0, which has just been published.
