### ISSUE TITLE
Will this work with connected-react-router

### ISSUE THREAD

**Issue by barrymichaeldoyle** [anastasiia-zolochevska/react-appinsights#13]
Our project is using the `connected-react-router` package for routing (since `react-router-redux` is deprecated and recommends using `connected-react-router`).

What's the best practice way to implement `react-appinsights` with `connected-react-router`?

**Comment by pviotti** [comment]
Hmmm... I'm not familiar with `connected-react-router`, but if you can have a `history` object somehow, you should be able to pass it to the init function, as in the [example in the readme](https://github.com/Azure/react-appinsights#track-router-changes).  
Unfortunately react-router v4 brought about some breaking changes (see https://github.com/Azure/react-appinsights/issues/12). I've just published v2.0.0, which hopefully deals with these changes in the least worst way.

**Comment by PaulInglis** [comment]
I'm using it with `connected-react-router` and it works fine.  As @pviotti says, as long as you have a valid `history` passed in then it should be good to go

**Comment by pviotti** [comment]
Yep. Closing this issue at it seems to be solved with v2.x.
