### ISSUE TITLE
Publish version 1.0.5 to NPM

### ISSUE THREAD

**Issue by CMihalcik** [anastasiia-zolochevska/react-appinsights#16]

**Comment by CMihalcik** [comment]
Looks like `withTracking` isn't available in the most recent NPM module (1.0.4)

**Comment by rbonini-doit** [comment]
This is a major issue for us as well - we need to use withTracking.

**Comment by MetaFight** [comment]
@anastasiia-zolochevska is this something you could help with?  I noticed a previous issue where you mentioned updating the npm package.

Cheers.

**Comment by anastasiia-zolochevska** [comment]
@pviotti Could you please help with this?  Let me know if you have permissions issues with npm.

**Comment by pviotti** [comment]
Sorry for the delay on this. I was trying to improve a couple of things (packaging, CI) before publishing v2, and I'm currently out of office. Will publish the new version early next week.

**Comment by pviotti** [comment]
I've just published v2.0.0 on NPM. It's a new major version since it breaks compatibility with the previous one: the old API based on inheritance has been replaced by the one based on the higher-order components mechanism. Enjoy (and open new issues if you have any)!

**Comment by exiadb** [comment]
@pviotti Could you add the breaking changes into releases CHANGELOG?

**Comment by pviotti** [comment]
Sure, here it is: https://github.com/Azure/react-appinsights/blob/master/CHANGELOG.md
