### ISSUE TITLE
react-appinsights.d.ts improvements

### ISSUE THREAD

**Issue by ghost** [anastasiia-zolochevska/react-appinsights#17]
I've been looking at `react-appinsights.d.ts`, and I think it has a few issues that need addressing.

These are the two (versioned) files I looked at to try and figure out what's going on:
 - https://github.com/Azure/react-appinsights/blob/9a21b648083d88db9336730da322552772ec7551/react-appinsights.d.ts
 - https://github.com/Azure/react-appinsights/blob/18c87a0fda91bff778ac9f58a9701142833b0165/src/ReactAI.js

The issues that I came across are:
 - `trackRouterChange()` is exposed as a function, but it doesn't appear to exist the JS source.
 - `TrackedComponent` is exported as a class type, but it's not used in `react-appinsights.d.ts`, and it doesn't appear to exist in the JS source.
 - The typings for `withTracking()` only allow for class components, and not for function components.
 - The typings for `withTracking()` strip the prop typings from the component passed to it.
   - i.e. `React.Component<TProps>` goes in, and `React.Component<{}>` comes out.

Fixing the first two issues is easy enough, I simply removed them from the definitions.

The third issue can be fixed by changing `React.Component` for `React.ComponentType`. `React.ComponentType` being a union type `type ComponentType<P = {}> = ComponentClass<P> | StatelessComponent<P>;`.

    withTracking(WrappedComponent: React.Component, componentName?: string): React.Component;
    withTracking(WrappedComponent: React.ComponentType, componentName?: string): React.ComponentType;

The forth issue can be fixed by adding an inferred generic type `TProps` for the props.

    withTracking(WrappedComponent: React.ComponentType, componentName?: string): React.ComponentType;
    withTracking<TProp>(WrappedComponent: React.ComponentType<TProp>, componentName?: string): React.ComponentType<TProp>;

So now `React.ComponentType<TProps>` goes in, and `React.ComponentType<TProps>` comes out.

And here's the definition file with the modifications applied: https://gist.github.com/AndyCJ/4336e9bef792f17d20bd645d3d7fc59d

**Comment by pviotti** [comment]
This was actually on my backlog, but I'm not very familiar with Typescript - so all the more reason to thank you for contributing this fix! 👍 It is now [integrated](https://github.com/Azure/react-appinsights/commit/c95406dc22a9716ea5b34f7e27d158c807b54e4d) in v2.0.0, which has just been published.

**Comment by ghost** [comment]
I'm glad it was of use!
