### ISSUE TITLE
o.AppInsights.downloadAndSetup is not a function

### ISSUE THREAD

**Issue by erikmoren** [anastasiia-zolochevska/react-appinsights#26]
Hi!

When hosting our webapp in Azure, we get `o.AppInsights.downloadAndSetup is not a function` in our console (and the app crashes). This seems to be because applicationinsights.js is already injected by Azure before react-appinsights tries to downloadAndSetup() it. Is it possible to do a check in react-appinsights if it has already been injected/downloaded?

**Comment by pviotti** [comment]
Hi! Thanks for reporting this.
From a quick search, it'd look like you have initialized AppInsights twice in your project: once with react-appinsights, and possibly once within your HTML skeleton page as well - as described in [this issue](https://github.com/harry671003/ng2-appinsights/issues/3).  
If you really cannot locate the other initialization that is causing this or can make a case for having two initializations in the same project, then I can consider adding a check as described [here](https://github.com/Microsoft/ApplicationInsights-JS/issues/579#issuecomment-380286859). But for now I'd suggest looking in your entire code base for the double initialization.  
Also, it'd be helpful to know more about your stack - I'm not sure what you mean by "injected by Azure".

**Comment by bernitorres** [comment]
I have a similar problem: a React app in a .NET Razor page, hosted on an Azure App Service, which has application insights enabled. 

App Insights can be enabled from the Azure portal for cloud service, with no code changes. I think that's what @erikmoren referred to with appinsights being injected by Azure.

**Comment by pviotti** [comment]
This should be fixed with the version now in the master branch which has been released as v3.0.0-rc.6 in the beta channel: `npm install --save react-appinsights@beta`.  
Feel free to comment here or open another issue if you still experience this.
