### ISSUE TITLE
Wonder why you don't use component name in metric name

### ISSUE THREAD

**Issue by SergeyKanzhelev** [anastasiia-zolochevska/react-appinsights#3]
I wonder why you decided to report component name as a custom property, not as part of the metric name here: https://github.com/anastasiia-zolochevska/react-appinsights/blob/master/src/components/TrackedComponent.js#L31

It is not wrong, I'm just curious

**Comment by anastasiia-zolochevska** [comment]
First of all to be able to group by Component Name. And if I'm not mistaken AI has limitation for the  amount of custom metrics.

**Comment by SergeyKanzhelev** [comment]
The same limitation applies to the cardinality of a custom property. However we are working on removing this limitation. So consider using metric name, not custom property please

**Comment by pviotti** [comment]
Hi @SergeyKanzhelev! Any updates on this issue two years later..? Would you still stand by this recommendation?  
(In the meantime I've released v2.0.0, with some maintenance changes)
