### ISSUE TITLE
Tracking script loaded and added twice

### ISSUE THREAD

**Issue by stjepan** [anastasiia-zolochevska/react-appinsights#4]
Application Insights tracking script is loaded and added twice:
First time, by AppInsights.downloadAndSetup(appInsightsOptions);
Second time, inside AppInsightsUsage.init(appInsightsOptions), which also calls AppInsights.downloadAndSetup(appInsightsOptions);

**Comment by pviotti** [comment]
Thanks for reporting this! I'm closing this issue, since it will be tracked and dealt with in #18.
