### ISSUE TITLE
How do I set ai.cloud.role?

### ISSUE THREAD

**Issue by rnarayana** [anastasiia-zolochevska/react-appinsights#40]
How do I set the cloud role for a react app?

```
import ReactAI from "react-appinsights";
if (ReactAI) {
    ReactAI.init({ instrumentationKey: xxxxxxxxx }, history);
    const appInsights = ReactAI.ai();
    appInsights.queue.push(() => {
        appInsights.context.addTelemetryInitializer(envelope => {
            envelope.tags['ai.device.roleName'] = "UI"; // Also tried with ai.cloud.role
        });
    });
}
```

This is not working.

**Comment by pviotti** [comment]
Have you tried using the `ReactAI.setAppContext` method to set the context attributes, as in [this test](https://github.com/Azure/react-appinsights/blob/master/test/ReactAI.test.js#L80-L99)?  
Also, I suggest using the upcoming v3.x, which is now in beta, and supports the new AppInsights SDK: `npm install --save react-appinsights@beta`. The API is slightly changed: you can find the docs [here](https://github.com/Azure/react-appinsights/blob/typescript-rewrite/README.md).

**Comment by rnarayana** [comment]
No luck @pviotti  I'm able to set custom properties and all, but not tags inside envelop. I'm able to do it with applicationinsights-js directly, but even if I get the root ai instance and set in react-appinsights, the value seems to get reset. Could you provide a small snippet on how to set this via react-appinsights?

Thanks!

**Comment by hiraldesai** [comment]
Hi @rnarayana - can you show me the code snippet after you tried it with the beta version? I'm guessing it should just be a matter of doing this.

```
ReactAI.rootInstance().addTelemetryInitializer(envelope => {
            envelope.tags = envelope.tags || {};
            envelope.tags['ai.device.roleName'] = "UI";
        });
```

**Comment by rnarayana** [comment]
With the above code, the error I get is: 
TypeError: react_appinsights__WEBPACK_IMPORTED_MODULE_5__.ReactAI.rootInstance is not a function

Steps:
Create a new react app with 
`npx create-react-app my-app`
Install react-appinsights beta
`npm i --save react-appinsights@beta`
Add the following lines of code in index.js
```
import { ReactAI } from 'react-appinsights';
ReactAI.initialize({ instrumentationKey: "xxxxx"});
ReactAI.rootInstance().addTelemetryInitializer(envelope => {
    envelope.tags = envelope.tags || {};
    envelope.tags['ai.device.roleName'] = "UI";
});

```

**Comment by pviotti** [comment]
Indeed `rootInstance` is not a function. If you try again with:
```javascript
ReactAI.rootInstance.addTelemetryInitializer(envelope => {
    envelope.tags = envelope.tags || {};
    envelope.tags['ai.device.roleName'] = "UI";
});
```
...that error should be solved.

**Comment by hiraldesai** [comment]
Of course, sorry my bad. `rootInstance` is a property not a function.
