### ISSUE TITLE
React.createClass is deprecated since React v15.5.0

### ISSUE THREAD

**Issue by Legogris** [anastasiia-zolochevska/react-appinsights#5]
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by barranger** [comment]
Created [this pull request](https://github.com/anastasiia-zolochevska/react-appinsights/pull/6) to handle this.

**Comment by anastasiia-zolochevska** [comment]
Merged Barranger's PR. Thank you both!
