### ISSUE TITLE
ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by aphleps** [anastasiia-zolochevska/react-appinsights#52]
I've been trying to get Azure Appinsights working with no luck. Followed the readme step by step in a contained React app with three components whose lifecycle I want to track.

Nothing arrives in the backend.

My Chrome dev tools console reports:
GET https://az416426.vo.msecnd.net/scripts/a/ai.0.js net::ERR_NAME_NOT_RESOLVED

Edit: I just realized that appinsights might just be blocked in this network. Google ads that appear in search for example are shown but cannot be clicked. Could this be the explanation?

**Comment by pviotti** [comment]
Yes, it sounds like something in the DNS resolution chain is blocking that specific domain. You may want to try using dig or other tools to troubleshoot this.
