### ISSUE TITLE
Type definition

### ISSUE THREAD

**Issue by antogg2004** [anastasiia-zolochevska/react-appinsights#7]
I would like to use the TrackedComponent however in my project I use typescript that extend 

 Component<IMyInterface, any>

Is it possible to add the "typed definitions"?

**Comment by anastasiia-zolochevska** [comment]
I’ll take a look. Also pull requests are very welcome :)

**Comment by antogg2004** [comment]
Thanks.. I will check if "someone" has some time :o))
