### ISSUE TITLE
AppInsights ignores updated Title tags

### ISSUE THREAD

**Issue by keithort** [anastasiia-zolochevska/react-appinsights#72]
I am using AppInsights v2.0.1 with React-Router-Dom v4.3.1 and mapping over an array of objects that contains my Route components. In those Route components, there is a Render function where I am setting a new document title tag with document.title. It writes to the interface just fine. The problem is when I switch routes, AppInsights is reporting the previous page's title tag with the new page's URL.  

I did a test using React Helmet v5.2.0 and setting the document title on each component. AppInsights was still behaving the same way.

Does any one know how we can get AppInsights to report the correct document title?

**Comment by hiraldesai** [comment]
Hi @keithort - can you please try our [new RC version](https://github.com/Azure/react-appinsights/tree/typescript-rewrite) which is fully rewritten in TypeScript and uses the new AI SDK? I think we noticed this issue during rewrite and added a 500ms delay on the trackPageView call to ensure that it records the values of the new page and not the old page.

You can install it by running this command:

```sh
npm install react-appinsights@beta
```

**Comment by keithort** [comment]
Thanks. It seems to work better however I am seeing one page view reported 2 or 3 times. I will dig into the issue and see if its my implementation or a bug. If it is a bug, I will open a new issue.
