### ISSUE TITLE
forget to push to npm?

### ISSUE THREAD

**Issue by 8man-mmie** [anastasiia-zolochevska/react-appinsights#8]
I'm still getting createClass deprecation error...

**Comment by Legogris** [comment]
@anastasiia-zolochevska: Any chance you could push an update to npm? Current version does not work with React16.

**Comment by dezoxel** [comment]
In case someone can't wait until it is published, you can always use commit hash in your dependencies in package.json:

```
"react-appinsights": "anastasiia-zolochevska/react-appinsights#4c6d23beffc7c5f2f1c1ab51e9fca7d58a79ced1",
```

The hash above points to the fix where it works with React 16.

**Comment by anastasiia-zolochevska** [comment]
Sorry, didn’t get notifications for some reason. Published. Thanks
