### ISSUE TITLE
usage with redux 

### ISSUE THREAD

**Issue by Jcbobo** [anastasiia-zolochevska/react-appinsights#82]
I'm  trying to integrate the library with a redux based application, but i'm having some issue with withAITracking HOC  both using react compose redux  method than apply first withAITracking than connect I receave errors inavalid component type (expected a string (for built-in components) or a class/function (for composite components) but got: object)

**Comment by hiraldesai** [comment]
Could it be an issue with ordering? I have used this package on redux based app and it works fine - this is a sample connected component with `withAITracking`.

```
import { withAITracking } from "react-appinsights";
import { connect } from "react-redux";
...
...
...
export default connect(
  mapStateToProps,
  mapDispatchToProps
)(withAITracking(RegisterPage));
```

**Comment by Jcbobo** [comment]
was the only order combination i did not try, thansk for the fast feedback.
