### ISSUE TITLE
Setting cloudRole example

### ISSUE THREAD

**Issue by yasso1am** [anastasiia-zolochevska/react-appinsights#84]
Not sure how to apply a "Question" label but that's what this is:
`version = "react-appinsights": "^3.0.0-rc.6",`

I've tried a number of things and for the life of me cannot set the `cloud_roleName` column like I have for other parts of my non-react applications.

I'm trying to use my own helper class to import and use where needed in the app. Here is `appinsights.ts`

```
import env from '../environment';
import { reactAI } from 'react-appinsights';
import { ApplicationInsights, ITraceTelemetry } from '@microsoft/applicationinsights-web';
import { ICustomProperties } from '@microsoft/applicationinsights-core-js';

import { history } from './history';

class Insights {
  private ai: ApplicationInsights;
  constructor() {
    this.ai = new ApplicationInsights({
      config: {
        instrumentationKey: `${env.appInsights.instrumentationKey}`,
        extensions: [reactAI],
        extensionConfig: {
          [reactAI.extensionId]: {
            debug: true,
            history: history,
          }
        }
      }
    });
    this.ai.loadAppInsights();
  }

  public setAuthenticatedUserContext = (patientId: string) => {
    this.ai.setAuthenticatedUserContext(patientId, undefined, true);
  };

  public clearAuthenticatedUserContext = () => {
    this.ai.clearAuthenticatedUserContext();
  };

  public trackTrace = (message: ITraceTelemetry, properties?: ICustomProperties) => {
    this.ai.trackTrace(message, properties);
  };
}

const AppInsightsService = new Insights();

export { AppInsightsService };
```

Previously, using the standard `applicationinsights-js` package,  I accomplished this through the following code:

```
AppInsights.queue.push( () => {
        AppInsights.context.addTelemetryInitializer( (envelope) => {
          envelope.tags['ai.cloud.role'] = 'My-awesome-role-name';
        });
      });
```
I'm sorry, but with all the changes between this package and the AppInsights team SDK, I'm struggling to replicate work I've done previously. If someone could direct me I would be super appreciative.

**Comment by hiraldesai** [comment]
Have you tried doing this?

`reactAI.setContext({"ai.cloud.role": "My-awesome-role-name"});`

This will ensure the supplied properties to the `setContext` get added to every single telemetry item sent from the client to AI. You need to do this any time after `this.ai.loadAppInsights();` is called.

This will get set as a custom dimension though - not sure if that's what you're looking for.

**Comment by yasso1am** [comment]
@hiraldesai I appreciate the suggestion, but as you noted it will get set as a custom dimension. I am looking specifically to set the `cloud_roleName` column in App Insights as that is what is used by our team for differentiating between our microservices. I also believe that is what the App Insights team uses to build the Application Map.

<img width="462" alt="Screen Shot 2019-04-25 at 6 16 11 PM" src="https://user-images.githubusercontent.com/39067243/56777428-66d4a000-6786-11e9-82ef-65794907f8d5.png">

**Comment by hiraldesai** [comment]
Hmm - maybe doing something like this might work? Add it just after `this.ai.loadAppInsights();`

```
this.ai.addTelemetryInitializer((envelope: ITelemetryItem) => {
  envelope.tags["ai.cloud.role"] = "My-awesome-role-name";
});
```

**Comment by yasso1am** [comment]
Once again @hiraldesai very much appreciate the quick responses and suggestions. I have tried all three below and unfortunately none have populated the `cloud_roleName` column in App Insights:

```
   reactAI.appInsights.addTelemetryInitializer( (envelope: ITelemetryItem) => {
      envelope.tags['ai.cloud.role'] = 'usingReactAI';
    });

    this.ai.appInsights.addTelemetryInitializer( (envelope: ITelemetryItem) => {
      envelope.tags['ai.cloud.role'] = 'usingAI+appInsights';
    });

    this.ai.addTelemetryInitializer( (envelope: ITelemetryItem) => {
      envelope.tags['ai.cloud.role'] = 'usingAI';
    });
```

This was done after calling `loadAppInsights()` and making sure all have value (reactAI/this.ai/this.ai.appInsights). I even tried returning true just for fun but that didn't work either...

**Comment by hiraldesai** [comment]
I tried it in my application as well, no joy. I can see the posted data in the track call to their API and it doesn't have these props in them. At this stage I'd have to revert this to the AI folks. Let me see if I can find someone who can answer this. Could be a bug in the new 2.0.0-rc1 SDK?

![image](https://user-images.githubusercontent.com/1005174/56778906-7c999380-678d-11e9-85ed-2332aa98fc69.png)

**Comment by yasso1am** [comment]
That's an interesting thought. I am able to call this.ai.setAuthenticatedUserContext(authUserString) (as well as clearAuthenticatedUserContext) so it seems I can access some of the built in functionality, but not all?

Thanks for reaching out to them!

**Comment by hiraldesai** [comment]
I got it working. I read the property type of tags wrong. Try this.

```typescript
    this.appInsights.addTelemetryInitializer((envelope: ITelemetryItem) => {
      envelope.tags = envelope.tags || [];
      envelope.tags.push({ "ai.cloud.role": "my-cloud-role" });
    });
```

![image](https://user-images.githubusercontent.com/1005174/56779223-c59e1780-678e-11e9-866e-8b9cae80ba49.png)


Tags are defined as this - that's why the previous syntax didn't work.

```typescript
    /**
     * System context property extensions that are not global (not in ctx)
     */
    tags?: Tags[];

export interface Tags {
    [key: string]: any;
}
```

**Comment by yasso1am** [comment]
Sweet! Is your `this.appInsights.addTelemetryInitializer` call equivalent to using my variable `this.ai`, as in the variable used to load: `this.ai.loadAppInsights();`?

**Comment by hiraldesai** [comment]
Yes - that's correct. My appinsights service is similar to yours. :-) just different variables.

https://gist.github.com/hiraldesai/e6b949ded30a3afb018901b28166f7eb

**Comment by yasso1am** [comment]
Thanks so much! @hiraldesai if I can help create any documentation let me know. I'm newer to typescript so reading the source code/interfaces is tricky enough for me.

**Comment by hiraldesai** [comment]
Thanks for offering to help, I'll certainly let you know if/when help needed. 

I feel like this particular thing belongs in the [main repo](https://github.com/Microsoft/ApplicationInsights-JS) only and I'm sure it will be covered by their 2.0.0 docs. Right now - these subtle differences between the 1.x and 2.0 are creating some confusion for everyone.

I believe that the whole `context` thing might also either become its own plugin outside of reactAI or become part of the `PropertiesPlugin`. I'm not entirely sure at this stage. I like how AI is now taking modular approach to add-ons and it's certainly going in the right direction.
